local M = {}

M.icons = {
	Text = "󰦨 ",
	Method = " ",
	Function = "󰡱 ",
	Constructor = " ",
	Field = " ",
	Variable = " ",
	Class = " ",
	Interface = " ",
	Module = "󰰏 ",
	Property = " ",
	Unit = "󰰧 ",
	Value = " ",
	Enum = " ",
	Keyword = " ",
	Snippet = " ",
	Color = " ",
	File = " ",
	Reference = " ",
	Folder = " ",
	EnumMember = " ",
	Constant = " ",
	Struct = " ",
	Event = " ",
	Operator = " ",
	TypeParameter = " ",
	Array = " ",
	Boolean = " ",
	Key = " ",
	Namespace = " ",
	Null = "󰟢 ",
	Number = " ",
	Object = "󰰕 ",
	Package = " ",
	String = " ",

	Version = "󰰪 ",
	Feature = " ",
}

return M
