local M = {}

M.icons = {
  Array = ' ',
  Boolean = ' ',
  Class = ' ',
  Color = ' ',
  Constant = ' ',
  Constructor = ' ',
  Enum = ' ',
  EnumMember = ' ',
  Event = ' ',
  Feature = ' ',
  Field = ' ',
  File = ' ',
  Folder = ' ',
  Function = '󰡱 ',
  Interface = ' ',
  Key = ' ',
  Keyword = ' ',
  Method = ' ',
  Module = '󰰏 ',
  Namespace = ' ',
  Null = '󰟢 ',
  Number = ' ',
  Object = '󰰕 ',
  Operator = ' ',
  Package = ' ',
  Property = ' ',
  Reference = ' ',
  Snippet = ' ',
  String = ' ',
  Struct = ' ',
  Text = '󰦨 ',
  TypeParameter = ' ',
  Unit = '󰰧 ',
  Value = ' ',
  Variable = ' ',
  Version = '󰰪 ',
}

M.exclude_types = {
  'checkhealth',
  'gitcommit',
  'help',
  'lazy',
  'lspinfo',
  'man',
  'mason',
  'noice',
  'oil',
  'trouble',
}

return M
